defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

permalink: /nieuws/:year/:month/:day/:title/

title: 'Raf Kappers in Huissen'